apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: serverless
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          args:
            - "-js"
            - "-m"
            - "8222"
          ports:
            - name: client
              containerPort: 4222
              hostPort: 4222
            - name: monitor
              containerPort: 8222
              hostPort: 8222
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: serverless
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
